version: '2'

services:
  elasticsearch:
#    build: /data/source/docker-elk/elasticsearch/
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
  logstash:
    #build: /data/source/docker-elk/logstash/
    #image: docker.elastic.co/logstash/logstash:5.2.1
    image: logstash
    volumes:
      - /vagrant/docker-elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /vagrant/docker-elk/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    #depends_on:
    links:
      - elasticsearch
  kibana:
    #build: /data/source/docker-elk/kibana/
    #image: docker.elastic.co/kibana/kibana:5.2.1
    image: kibana
    volumes:
      - /vagrant/docker-elk/kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    #depends_on:
    links:
      - elasticsearch
